# Generated by Django 4.2 on 2023-08-30 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recruiter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='applicantverifiedDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ApplicantID', models.CharField(blank=True, max_length=50, null=True)),
                ('Image', models.ImageField(null=True, upload_to='Applicant_Photo')),
                ('Salutation', models.CharField(blank=True, max_length=10, null=True)),
                ('Name', models.CharField(blank=True, max_length=50, null=True)),
                ('Email', models.EmailField(blank=True, max_length=100, null=True)),
                ('Mobile', models.IntegerField(blank=True, null=True)),
                ('Location', models.CharField(blank=True, max_length=100, null=True)),
                ('Qualification', models.CharField(blank=True, max_length=100, null=True)),
                ('Field', models.CharField(blank=True, max_length=100, null=True)),
                ('University', models.CharField(blank=True, max_length=100, null=True)),
                ('Duration', models.CharField(blank=True, max_length=100, null=True)),
                ('CGPA', models.FloatField(blank=True, null=True)),
                ('Company', models.CharField(max_length=100)),
                ('Designation', models.CharField(max_length=100)),
                ('Experience', models.CharField(max_length=20)),
                ('Skills', models.CharField(max_length=50)),
                ('Linkedin', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='contactDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=100)),
                ('Subject', models.CharField(max_length=50)),
                ('Message', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='contactresponseDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=100)),
                ('Subject', models.CharField(max_length=50)),
                ('Message', models.CharField(max_length=1000)),
                ('Admin_Name', models.CharField(max_length=50)),
                ('Image', models.ImageField(upload_to='Response')),
                ('Remarks', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='recruiterverifiedDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=100, null=True)),
                ('RecruiterID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruiter.recruiterdb')),
            ],
        ),
    ]
