# Generated by Django 4.2 on 2023-09-10 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_jobsverifieddb'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicantverifieddb',
            name='Resume',
            field=models.FileField(blank=True, null=True, upload_to='Resume'),
        ),
    ]
