# Generated by Django 4.2 on 2023-08-30 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='jobsDB',
            fields=[
                ('RecruiterID', models.CharField(blank=True, max_length=20, null=True)),
                ('Company_Name', models.CharField(max_length=50, null=True)),
                ('Logo', models.ImageField(null=True, upload_to='jobimages')),
                ('JobID', models.AutoField(primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=50)),
                ('Email', models.EmailField(blank=True, max_length=50, null=True)),
                ('Location', models.CharField(max_length=50)),
                ('Type', models.CharField(max_length=20)),
                ('Published', models.DateField()),
                ('Deadline', models.DateField(blank=True, null=True)),
                ('Experience', models.CharField(default='Any', max_length=100)),
                ('Gender', models.CharField(default='Any', max_length=20)),
                ('Salary', models.CharField(max_length=50)),
                ('Qualification', models.CharField(max_length=100)),
                ('Description', models.CharField(blank=True, max_length=1000, null=True)),
                ('Remarks', models.CharField(blank=True, max_length=50)),
                ('Status', models.CharField(default='Pending', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='recruiterDB',
            fields=[
                ('RecruiterID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=50)),
                ('Password', models.CharField(max_length=50)),
                ('Logo', models.ImageField(upload_to='recruiterlogos')),
            ],
        ),
        migrations.CreateModel(
            name='responsibilities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('res1', models.CharField(blank=True, max_length=100, null=True)),
                ('res2', models.CharField(blank=True, max_length=100, null=True)),
                ('res3', models.CharField(blank=True, max_length=100, null=True)),
                ('res4', models.CharField(blank=True, max_length=100, null=True)),
                ('res5', models.CharField(blank=True, max_length=100, null=True)),
                ('res6', models.CharField(blank=True, max_length=100, null=True)),
                ('res7', models.CharField(blank=True, max_length=100, null=True)),
                ('res8', models.CharField(blank=True, max_length=100, null=True)),
                ('res9', models.CharField(blank=True, max_length=100, null=True)),
                ('res10', models.CharField(blank=True, max_length=100, null=True)),
                ('JobID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruiter.jobsdb')),
            ],
        ),
        migrations.CreateModel(
            name='recruiterprofileDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Logo', models.ImageField(blank=True, null=True, upload_to='recruiterdocuments')),
                ('Name', models.CharField(blank=True, max_length=100, null=True)),
                ('Email', models.EmailField(blank=True, max_length=100, null=True)),
                ('Description', models.CharField(blank=True, max_length=500, null=True)),
                ('Location', models.CharField(blank=True, max_length=100, null=True)),
                ('Contact', models.CharField(blank=True, max_length=100, null=True)),
                ('Doc1', models.ImageField(blank=True, null=True, upload_to='recruiterdocuments')),
                ('Doc2', models.ImageField(blank=True, null=True, upload_to='recruiterdocuments')),
                ('Doc3', models.ImageField(blank=True, null=True, upload_to='recruiterdocuments')),
                ('Remarks', models.CharField(blank=True, max_length=100, null=True)),
                ('Status', models.CharField(default='Pending', max_length=20)),
                ('RecruiterID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruiter.recruiterdb')),
            ],
        ),
        migrations.CreateModel(
            name='otherrequirements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('req1', models.CharField(blank=True, max_length=100, null=True)),
                ('req2', models.CharField(blank=True, max_length=100, null=True)),
                ('req3', models.CharField(blank=True, max_length=100, null=True)),
                ('req4', models.CharField(blank=True, max_length=100, null=True)),
                ('req5', models.CharField(blank=True, max_length=100, null=True)),
                ('JobID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruiter.jobsdb')),
            ],
        ),
        migrations.CreateModel(
            name='benefits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ben1', models.CharField(blank=True, max_length=100, null=True)),
                ('ben2', models.CharField(blank=True, max_length=100, null=True)),
                ('ben3', models.CharField(blank=True, max_length=100, null=True)),
                ('ben4', models.CharField(blank=True, max_length=100, null=True)),
                ('ben5', models.CharField(blank=True, max_length=100, null=True)),
                ('JobID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruiter.jobsdb')),
            ],
        ),
    ]
