# Generated by Django 4.2 on 2023-09-02 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0002_recruiterprofiledb_website'),
    ]

    operations = [
        migrations.CreateModel(
            name='jobapplyDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=50)),
                ('ApplicantID', models.CharField(max_length=20)),
                ('JobID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruiter.jobsdb')),
            ],
        ),
    ]
