# Generated by Django 4.2 on 2023-09-08 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0004_alter_jobsdb_remarks'),
    ]

    operations = [
        migrations.CreateModel(
            name='profilebookmarkDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ApplicantID', models.CharField(max_length=20)),
                ('RecruiterID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruiter.recruiterdb')),
            ],
        ),
    ]
