# Generated by Django 4.2 on 2023-08-30 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='applicantDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ApplicantID', models.CharField(blank=True, max_length=50, null=True)),
                ('Image', models.ImageField(blank=True, null=True, upload_to='Applicant_Photo')),
                ('Salutation', models.CharField(blank=True, max_length=10, null=True)),
                ('Name', models.CharField(blank=True, max_length=50, null=True)),
                ('Email', models.EmailField(blank=True, max_length=100, null=True)),
                ('Mobile', models.IntegerField(blank=True, null=True)),
                ('Location', models.CharField(blank=True, max_length=100, null=True)),
                ('Qualification', models.CharField(blank=True, max_length=100, null=True)),
                ('Field', models.CharField(blank=True, max_length=100, null=True)),
                ('University', models.CharField(blank=True, max_length=100, null=True)),
                ('Duration', models.CharField(blank=True, max_length=100, null=True)),
                ('CGPA', models.FloatField(blank=True, null=True)),
                ('Company', models.CharField(max_length=100)),
                ('Designation', models.CharField(max_length=100)),
                ('Experience', models.CharField(max_length=20)),
                ('Skills', models.CharField(max_length=50)),
                ('Linkedin', models.CharField(blank=True, max_length=50, null=True)),
                ('Status', models.CharField(default='Pending', max_length=10)),
                ('Remarks', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='clientDB',
            fields=[
                ('ClientID', models.AutoField(primary_key=True, serialize=False)),
                ('Email', models.EmailField(blank=True, max_length=50, null=True)),
                ('password', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
