# Generated by Django 4.2 on 2023-09-04 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0003_jobsavedb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicantdb',
            name='Remarks',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
