# Generated by Django 4.2 on 2023-09-10 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0005_applicantdb_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicantdb',
            name='Resume',
            field=models.FileField(blank=True, null=True, upload_to='resume/'),
        ),
    ]
